FROM node:krypton-slim AS dependencies-env

COPY . /app
WORKDIR /app

RUN npm ci && \
    npm cache clean --force && \
    npm cache verify

COPY . /app/
COPY --from=dependencies-env /app/node_modules /app/node_modules

WORKDIR /app

RUN npm run build
