services:
  nginx:
    image: nginx:1.29
    command: ["nginx", "-g", "daemon off;"]
    ports:
      - published: 80
        target: 80
    restart: unless-stopped

  mysql:
    image: mysql:9.6
    ports:
      - published: 3306
        target: 3306
    volumes:
      - type: volume
        source: mysql_data
        target: /var/lib/mysql
    env_file:
      - path: .env
    restart: unless-stopped

  beanstalk:
    image: ghcr.io/beanstalkd/beanstalkd:latest
    ports:
      - published: 11300
        target: 11300
    command: ["-b", "/var/lib/beanstalkd"]
    volumes:
      - type: volume
        source: beanstalkd_data
        target: /var/lib/beanstalkd
    restart: unless-stopped

  laravel:
    build:
      context: ./apps/core
      dockerfile: dockerfile
    ports:
      - published: 9000
        target: 9000
    command: ["php-fpm"]
    restart: unless-stopped

  reactrouter:
    build:
      context: ./apps/app
      dockerfile: dockerfile
    command: ["pnpm", "start"]
    ports:
      - published: 3000
        target: 3000
    restart: unless-stopped

volumes:
  mysql_data:
  beanstalkd_data:
  laravel_data:
